### ISSUE TITLE
Windows 10. No module named 'resource'

### ISSUE THREAD

**Issue by devdimit93** [stablecabal/gyre#12]
ModuleNotFoundError: No module named 'resource'  appears when installing gyre on anaconda or miniconda on windows 10. 
```
(gyre) E:\gyre\ge2\gyre>python server.py
Traceback (most recent call last):
  File "E:\gyre\ge2\gyre\server.py", line 1, in <module>
    from gyre import server
  File "E:\gyre\ge2\gyre\gyre\server.py", line 48, in <module>
    patch_setrlimit()
  File "E:\gyre\ge2\gyre\gyre\patching.py", line 18, in patch_setrlimit
    import resource
ModuleNotFoundError: No module named 'resource' 
```
Gyre is installed according to these instructions https://gyre.ai/docs/install/manual#running
Installation on Ubuntu goes without any problems.
Installing the 'resource' package manually via pip does not change the error. 
Installation via "install_or_update.cmd" also work correctly.

**Comment by hafriedlander** [comment]
Hi,

Thanks. Just looking into it, "resource" is unix-specific. install_or_update.cmd works on windows because it uses a pinned version of gyre prior to this bug being introduced.

In the meantime, you can check out hash 0aef19a2482ff2cd36a54ba885547be6c975b8b4 (`git checkout 0aef19a2482ff2cd36a54ba885547be6c975b8b4`) but I should be able to fix this fairly quickly.
